# 1. Marie located in Back Alley
[npc_marie]
    _prefix = "marie.alley."
    _start = "small_talk"
    small_talk = { description = "small_talk.dialog", options = [
        { description = "small_talk.option_1", to = "protests" },
        { description = "small_talk.option_2", to = "sylvasta" },
        { description = "small_talk.option_q", to = "small_talk", mustExit = true }
    ] }
    protests = { description = "protests.dialog", options = [
        { description = "protests.option_1", to = "confirm" },
        { description = "protests.option_q", to = "small_talk", mustExit = true }
    ] }
    sylvasta = { description = "sylvasta.dialog", options = [
        { description = "sylvasta.option_1", to = "confirm" },
        { description = "sylvasta.option_q", to = "small_talk", mustExit = true }
    ] }
    confirm = { description = "confirm.dialog", options = [
        { description = "confirm.option_q", to = "small_talk", mustExit = true }
    ] }

    recon = { description = "recon.dialog", options = [
        { description = "recon.option_q", to = "waiting", mustExit = true }
    ] }
    waiting = { description = "waiting.dialog", options = [
        { description = "waiting.option_q", to = "waiting", mustExit = true }
    ] }

    mission_brief = { description = "mission_brief.dialog", options = [
        { description = "mission_brief.option_q", to = "mission_brief", mustExit = true }
    ] }

# 2. Random City NPC located in the City Centre
[npc_city_centre]
    _prefix = "city_centre.npc."
    _start = "small_talk"
    small_talk = { description = "small_talk.dialog", options = [
        { description = "small_talk.option_1", to = "protestors" },
        { description = "small_talk.option_2", to = "enquire" },
        { description = "small_talk.option_q", to = "small_talk", mustExit = true }
    ] }
    protestors = { description = "protestors.dialog", options = [
        { description = "protestors.option_1", to = "leaflet" },
        { description = "small_talk.option_q", to = "small_talk", mustExit = true }
    ] }
    enquire = { description = "enquire.dialog", options = [
        { description = "protestors.option_1", to = "leaflet", },
        { description = "small_talk.option_q", to = "small_talk", mustExit = true }
    ] }
    leaflet = { description = "leaflet.dialog", options = [
        { description = "leaflet.option_1", to= "small_talk", mustExit = true }
    ] }
    #recon = { description = "testing", options = [
    #    { description = "sususus!", to = "recon", mustExit = true }
    #] }

# 3. Old Man located in Forest
[npc_old_man]
    _prefix = "forest.old_man."
    _start = "small_talk"
    small_talk = { description = "small_talk.dialog", options = [
        { description = "small_talk.option_1", to = "request" },
        { description = "small_talk.option_q", to = "small_talk", mustExit = true }
    ] }
    request = { description = "request.dialog", options = [
        { description = "request.option_1", to = "small_talk", mustExit = true },
        { description = "request.option_q", to = "small_talk", mustExit = true }
    ] }
    praise = { description = "praise.dialog", options = [
        { description = "praise.option_q", to = "praise", mustExit = true }
    ] }

# 4. Protestors located on Street
[npc_protestors]
    _prefix = "street.protestors."
    _start = "small_talk"
    small_talk = { description = "small_talk.dialog", options = [
        { description = "small_talk.option_1", to = "enquire" },
        { description = "small_talk.option_2", to = "small_talk", mustExit = true }
    ] }
    enquire = { description = "enquire.dialog", options = [
        { description = "enquire.option_1", to = "leaks" },
        { description = "enquire.option_2", to = "confrontation" }
    ] }
    leaks = { description = "leaks.dialog", options = [
        { description = "leaks.option_1", to = "small_talk", mustExit = true }
    ] }
    confrontation = { description = "confrontation.dialog", options = [
        { description = "confrontation.option_1", to = "small_talk", mustExit = true },
        { description = "confrontation.option_2", to = "small_talk", mustExit = true }
    ] }

# 5. Security guard stationed at Medical Centre
[npc_security_guard]
    _prefix = "medical_centre.guard."
    _start = "small_talk"
    small_talk = { description = "small_talk.dialog", options = [
        { description = "small_talk.option_q", to = "small_talk", mustExit = true }
    ] }

# 6. Shop shopkeeper in the Shop
[npc_shopkeeper]
    _prefix = "shop.npc."
    _start = "index"
    index = { description = "index", options = [
        { description = "leave", to = "index", mustExit = true }
    ] }
    recon = { description = "recon", options = [
        { description = "leave", to = "recon", mustExit = true }
    ] }
    stealth = { description = "stealth", options = [
        { description = "leave", to = "stealth", mustExit = true }
    ] }

# 7. Receptionist located in Apartments
[npc_receptionist]
    _prefix = "apartments.receptionist."
    _start = "first_encounter"
    first_encounter = { description = "first_encounter.dialog", options = [
        { description = "first_encounter.option_1", to = "protestors" },
        { description = "first_encounter.option_q", to = "repeated", mustExit = true }
    ] }
    protestors = { description = "protestors.dialog", options = [
        { description = "protestors.option_1", to = "protestors2" },
        { description = "protestors.option_q", to = "repeated" }
    ] }
    protestors2 = { description = "protestors2.dialog", options = [
        { description = "protestors2.option_q", to = "repeated" }
    ] }
    repeated = { description = "repeated.dialog", options = [
        { description = "repeated.option_1", to = "protestors" },
        { description = "repeated.option_q", to = "repeated", mustExit = true }
    ] }

# 8. TV located in Apartments
[home_tv]
    _prefix = "home.tv."
    _start = "first_on"
    first_on = { description = "first_on.dialog", options = [
        { description = "keep_watching", to = "dialog_a" },
        { description = "off", to = "first_on", mustExit = true }
    ] }
    dialog_a = { description = "first_on.dialog_a", options = [
        { description = "keep_watching", to = "dialog_b" },
        { description = "off", to = "first_on", mustExit = true }
    ] }
    dialog_b = { description = "first_on.dialog_b", options = [
        { description = "keep_watching", to = "dialog_c" },
        { description = "off", to = "first_on", mustExit = true }
    ] }
    dialog_c = { description = "first_on.dialog_c", options = [
        { description = "off", to = "first_on", mustExit = true }
    ] }

# 9. Communicator device with Marie
[comms_marie]
    _prefix = "marie.comms."
    _start = "orientation"
    
    orientation = { description = "orientation.dialog", options = [
        { description = "orientation.option_1", to = "directions" },
        { description = "orientation.option_2", to = "hear" },
        { description = "orientation.option_q", to = "orientation", mustExit = true }
    ] }
    directions = { description = "directions.dialog", options = [
        { description = "directions.option_q", to = "orientation" }
    ] }
    hear = { description = "hear.dialog", options = [
        { description = "hear.option_q", to = "orientation" }
    ] }

    complaint = { description = "complaint.dialog", options = [
        { description = "complaint.option_q", to = "complaint", mustExit = true }
    ] }

    in_position = { description = "in_position.dialog", options = [
        { description = "in_position.option_1", to = "distraction" }
    ] }
    distraction = { description = "distraction.dialog", options = [
        #{ description = "in_position.option_1", to = "coast_is_clear" }
    ] }
    coast_is_clear = { description = "coast_is_clear.dialog", options = [
        { description = "coast_is_clear.option_q", to = "gogogo", mustExit = true }
    ] }
    gogogo = { description = "gogogo.dialog", options = [
        { description = "gogogo.option_q", to = "gogogo", mustExit = true }
    ] }
