# 1. Marie located in Back Alley
[npc_marie]
    _prefix = "marie.alley."
    _start = "small_talk"
    small_talk = { description = "small_talk", options = [
        { description = "leave", to = "small_talk", mustExit = true }
    ] }

# 2. Random City NPC located in the City Centre
[npc_city_centre]
    _prefix = "city_centre.npc."
    _start = "small_talk"
    small_talk = { description = "small_talk", options = [
        { description = "leave", to = "small_talk", mustExit = true }
    ] }

# 3. Old Man located in Forest
# out of scope until (2.) or (sq1.)
[npc_old_man]
    _prefix = "forest.old_man."
    _start = "small_talk"
    small_talk = { description = "small_talk", options = [
        { description = "leave", to = "small_talk", mustExit = true }
    ] }

# 4. Protestors located on Street
[npc_protestors]
    _prefix = "street.protestors."
    _start = "small_talk"
    small_talk = { description = "small_talk", options = [
        { description = "leave", to = "small_talk", mustExit = true }
    ] }

# 5. Security guard stationed at Medical Centre
[npc_security_guard]
    _prefix = "medical_centre.guard."
    _start = "small_talk"
    small_talk = { description = "small_talk", options = [
        { description = "leave", to = "small_talk", mustExit = true }
    ] }

# 6. Shop shopkeeper in the Shop
[npc_shopkeeper]
    _prefix = "shop.npc."
    _start = "small_talk"
    small_talk = { description = "small_talk", options = [
        { description = "leave", to = "small_talk", mustExit = true }
    ] }

# 7. Receptionist located in Apartments
[npc_receptionist]
    _prefix = "apartments.receptionist."
    _start = "first_encounter"
    first_encounter = { description = "first_encounter.dialog", options = [
        { description = "first_encounter.option_1", to = "protestors" },
        { description = "first_encounter.option_q", to = "repeated", mustExit = true }
    ] }
    protestors = { description = "protestors.dialog", options = [
        { description = "protestors.option_1", to = "protestors2" },
        { description = "protestors.option_q", to = "repeated" }
    ] }
    protestors2 = { description = "protestors2.dialog", options = [
        { description = "protestors2.option_q", to = "repeated" }
    ] }
    repeated = { description = "repeated.dialog", options = [
        { description = "repeated.option_1", to = "protestors" },
        { description = "repeated.option_q", to = "repeated", mustExit = true }
    ] }

# 8. TV located in Apartments
[home_tv]
    _prefix = "home.tv."
    _start = "first_on"
    first_on = { description = "first_on", options = [
        { description = "off", to = "first_on", mustExit = true }
    ] }
